ShopWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopWeb.Models;

namespace ShopWeb.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Index(MemberLoginViewModel memberViewModel)
        {
            if (ModelState.IsValid)
            {
                ViewBag.ErrorMessage = null;
                ShopBusinessLogic.LoginMember loginMember = new ShopBusinessLogic.LoginMember();
                //string userPhone = Request.Params["phone"];
                //ShopWeb.Models.MemberViewModel memberViewModel = new MemberViewModel();
                string userPhone = memberViewModel.mem_phone;
                //string userPwd = Request.Params["password"];
                string userPwd = memberViewModel.mem_pwd;
                string truePwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                //var memView = new MemberViewModel();
                if (truePwd == userPwd)
                {
                    //memView.mem_name = loginMember.GetMemberByPhone(userPhone).mem_name;
                    //memView.mem_phone = loginMember.GetMemberByPhone(userPhone).mem_phone;
                    //memView.mem_pwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                    string mem_name = loginMember.GetMemberByPhone(userPhone).mem_name;
                    string mem_phone = loginMember.GetMemberByPhone(userPhone).mem_phone;
                    string mem_pwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                    Session["mem_name"] = mem_name;
                    Session["mem_phone"] = mem_phone;
                    Session["mem_pwd"] = mem_pwd;
                    Session["has_login"] = "true";
                    Session.Timeout = 30;
                    if (Session["ReturnToPurchaseCar"] != null) return Redirect("/PurchaseCar");
                    else if (Session["ReturnToWishList"] != null) return Redirect("/WishList");
                    else if (Session["ReturnToPurchaseList"] != null) return Redirect("/PurchaseList");
                    else if (Session["ReturnToMemberInfo"] != null) return Redirect("/MemberInfo");
                    else return Redirect("/Home");
                }
                else
                {
                    ViewBag.LoginErrorMessage = "用户名或密码错误";
                    return View();
                }
            }
            else return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Login(MemberLoginViewModel memberViewModel)
        {
            if (ModelState.IsValid)
            {
                ShopBusinessLogic.LoginMember loginMember = new ShopBusinessLogic.LoginMember();
                //string userPhone = Request.Params["phone"];
                //ShopWeb.Models.MemberViewModel memberViewModel = new MemberViewModel();
                string userPhone = memberViewModel.mem_phone;
                //string userPwd = Request.Params["password"];
                string userPwd = memberViewModel.mem_pwd;
                string truePwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                //var memView = new MemberViewModel();
                if (truePwd == userPwd)
                {
                    //memView.mem_name = loginMember.GetMemberByPhone(userPhone).mem_name;
                    //memView.mem_phone = loginMember.GetMemberByPhone(userPhone).mem_phone;
                    //memView.mem_pwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                    string mem_name = loginMember.GetMemberByPhone(userPhone).mem_name;
                    string mem_phone = loginMember.GetMemberByPhone(userPhone).mem_phone;
                    string mem_pwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                    Session["mem_name"] = mem_name;
                    Session["mem_phone"] = mem_phone;
                    Session["mem_pwd"] = mem_pwd;
                    Session["has_login"] = "true";
                    Session.Timeout = 30;
                    return Redirect("/Home");
                }
                else
                {
                    ViewBag.ErrorMessage = "用户名或密码错误";
                    return View();
                }
            }
            else return Redirect("/Login");
        }

        /*[HttpPost]
        public JsonResult Check_pwd(MemberViewModel memberViewModel)
        {

            ShopBusinessLogic.LoginMember loginMember = new ShopBusinessLogic.LoginMember();
            string inputPhone = memberViewModel.mem_phone;
            string inputPwd = memberViewModel.mem_pwd;
            string truePwd = loginMember.GetMemberByPhone(inputPhone).mem_pwd;
            if ( inputPwd!=truePwd)
            {
                return Json("输入密码错误", JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }*/


        /*
        var memView = new MemberViewModel();
        if (loginMember.GetMemberByPhone(userPhone).mem_pwd == userPwd)
        {
            memView.mem_name = loginMember.GetMemberByPhone(userPhone).mem_name;
            memView.mem_phone = loginMember.GetMemberByPhone(userPhone).mem_phone;
            memView.mem_pwd = loginMember.GetMemberByPhone(userPhone).mem_pwd;
            Session["mem_name"] = memView.mem_name;
            Session["mem_phone"] = memView.mem_phone;
            Session["mem_pwd"] = memView.mem_pwd;
            Session["has_login"] = "true";
            Session.Timeout = 1;
            return Redirect("/Home");
        }
        else
        {
            return RedirectToAction("Index");
        }
        */
        //}

        public ActionResult LoginOut()
        {
            Session.Clear();
            return Redirect("/Home");
        }

        /*public ActionResult Get(string id)
        {
            ShopBusinessLogic.Manager manager = new ShopBusinessLogic.Manager();
            var membinfo = manager.GetMemberId(id);
            if (membinfo == null) return HttpNotFound();
            var memberview = new MemberViewModel()
            {
                id = membinfo.id,
                pwd = membinfo.pwd,
                nname = membinfo.nname
            };

            return View(memberview);

            /*
           var meminfo = members.Where(now => now.id == id).FirstOrDefault();
           if (meminfo == null)
               return HttpNotFound();
           ViewBag.MemberInfo = meminfo;
           return View();
           */
        /*}

        public ActionResult ShowInfo(string id)
        //{

            ShopBusinessLogic.Manager manager = new ShopBusinessLogic.Manager();
            var meminfo = manager.GetAllMember().Select(member => new MemberViewModel()
            //{
                id = member.id,
                pwd = member.pwd,
                nname = member.nname
            }).ToList();
            var resViewModel = new ResModel()
            //{
                id = meminfo.Count.ToString(),
                pwd = "222",
                nname = "333",
                memberList = meminfo
            };
            return View(resViewModel);
           */
    }
}

    

ShopWeb/Controllers/PurchaseListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopWeb.Models;

namespace ShopWeb.Controllers
{
    public class PurchaseListController : Controller
    {
        // GET: PurchaseList
        
        public ActionResult Index()
        {
            if (Session["has_login"] == null)
            {
                if (Session["ReturnToPurchaseList"] == null) Session["ReturnToPurchaseList"] = "true";
                else Session["ReturnToPurchaseList"] = null;
                return Redirect("/Login");
            }
            else
            {
                Session.Remove("ReturnToPurchaseList");
                ShopBusinessLogic.MemberPurchase memberPurchase = new ShopBusinessLogic.MemberPurchase();
                var p_list = memberPurchase.getPurchaseLists(Session["mem_phone"].ToString()).Select(p_info => new MemberPurchaseListViewModel()
                {
                    plist_id=p_info.plist_id,
                    goods_id = p_info.goods_id,
                    goods_name = p_info.goods_name,
                    goods_img_path=memberPurchase.getGoods(p_info.goods_id).goods_img_path,
                    goods_num = p_info.goods_num,
                    date=p_info.date,     
                    unit_price = p_info.unit_price,
                    total_price = p_info.total_price,
                }).ToList();
                var resView = new MemberPurchaseListViewModel()
                {
                    mem_phone = Session["mem_phone"].ToString(),
                    purchase_lists = p_list,
                };
                //return PartialView("PlistPart1", resView);
                return View(resView);
            }
        }
        
        [HttpPost]
        public ActionResult Search(MemberPurchaseListViewModel memberPurchaseListViewModel)
        {
            string search_id = memberPurchaseListViewModel.search_id;
            string mem_phone = Session["mem_phone"].ToString();
            ShopBusinessLogic.MemberPurchase memberPurchase = new ShopBusinessLogic.MemberPurchase();
            if(search_id==null)
            {
                var p_list = memberPurchase.getPurchaseLists(mem_phone).Select(p_info => new MemberPurchaseListViewModel()
                {
                    plist_id = p_info.plist_id,
                    goods_id = p_info.goods_id,
                    goods_name = p_info.goods_name,
                    goods_img_path = memberPurchase.getGoods(p_info.goods_id).goods_img_path,
                    goods_num = p_info.goods_num,
                    date = p_info.date,
                    unit_price = p_info.unit_price,
                    total_price = p_info.total_price,
                }).ToList();
                var resView = new MemberPurchaseListViewModel()
                {
                    mem_phone = mem_phone,
                    purchase_lists = p_list,
                };
                return PartialView("PlistPart1", resView);
            }
            else
            {
                var p_list = memberPurchase.getPurchaseListsBySearchId(mem_phone,search_id).Select(p_info => new MemberPurchaseListViewModel()
                {
                    plist_id = p_info.plist_id,
                    goods_id = p_info.goods_id,
                    goods_name = p_info.goods_name,
                    goods_img_path = memberPurchase.getGoods(p_info.goods_id).goods_img_path,
                    goods_num = p_info.goods_num,
                    date = p_info.date,
                    unit_price = p_info.unit_price,
                    total_price = p_info.total_price,
                }).ToList();
                var resView = new MemberPurchaseListViewModel()
                {
                    mem_phone = mem_phone,
                    purchase_lists = p_list,
                };
                return PartialView("PlistPart1", resView);
            }
        }

        [HttpPost]
        public JsonResult SelectGoodsToBuy(PurchaseHomeTotalInfo purchaseHomeTotalInfo)
        {
            Session.Remove("ReturnToPurchaseCar");
            string mem_phone = Session["mem_phone"].ToString();
            var goods_items = purchaseHomeTotalInfo.selected_goods_list;
            ShopBusinessLogic.MemberPurchase memberPurchase = new ShopBusinessLogic.MemberPurchase();
            DateTime now_time = DateTime.Now;
            foreach(var goods in goods_items)
            {
                var plist_id = now_time.ToString("yyyyMMddHHmmssfff") + mem_phone;
                memberPurchase.addPurchaseLists(plist_id,mem_phone, goods.goods_id, goods.goods_num,now_time);
                memberPurchase.deletePurchaseCar(mem_phone, goods.goods_id);
            }
            return Json("购买商品成功");
        }
    }
}

ShopWeb/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopWeb.Models;

namespace ShopWeb.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(MemberSignViewModel memberSignViewModel)
        {
            ViewBag.SignUpErrorMessage = null;
            ShopBusinessLogic.LoginMember loginMember = new ShopBusinessLogic.LoginMember();
            //string userPhone = Request.Params["phone"];
            //string userPwd = Request.Params["password"];
            string userPhone = memberSignViewModel.mem_phone;
            string userName = memberSignViewModel.mem_name;
            string userPwd = memberSignViewModel.mem_pwd;
            string userRePwd = memberSignViewModel.mem_re_pwd;
            if(ModelState.IsValid)
            {
                if(loginMember.SignUpMemberByPhone(userPhone, userPwd,userName))
                {
                    Session["mem_name"] = loginMember.GetMemberByPhone(userPhone).mem_name;
                    Session["mem_phone"] = loginMember.GetMemberByPhone(userPhone).mem_phone;
                    Session["mem_pwd"] = loginMember.GetMemberByPhone(userPhone).mem_pwd;
                    Session["has_login"] = "true";
                    Session.Timeout = 10;
                    return Redirect("/Home");
                }
                else
                {
                    ViewBag.SignUpErrorMessage = "该手机号已注册";
                    return View();
                }
            }
            return View();
        }

        public ActionResult LoginOut()
        {
            Session.Clear();
            return Redirect("/Home");
        }
    }
}

ShopWeb/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopWeb.Models;

namespace ShopWeb.Controllers
{
    public class WishListController : Controller
    {
        // GET: WishList
        public ActionResult Index()
        {
            if (Session["has_login"] == null)
            {
                if (Session["ReturnToWishList"] == null) Session["ReturnToWishList"] = "true";
                else Session["ReturnToWishList"] = null;
                return Redirect("/Login");
            }
            else
            {
                Session.Remove("ReturnToWishList");
                ShopBusinessLogic.MemberPurchase memberPurchase = new ShopBusinessLogic.MemberPurchase();
                var wish_list = memberPurchase.getWishLists(Session["mem_phone"].ToString()).Select(wish_info => new MemberWishListViewModel()
                {
                    goods_id=wish_info.goods_id,
                    goods_name=memberPurchase.getGoods(wish_info.goods_id).goods_name,
                    goods_unit_price=memberPurchase.getGoods(wish_info.goods_id).goods_price,
                    goods_img_path=memberPurchase.getGoods(wish_info.goods_id).goods_img_path,
                }).ToList();
                var resView = new MemberWishListViewModel()
                {
                    mem_phone = Session["mem_phone"].ToString(),
                    wish_lists=wish_list,
                };
                return View(resView);
            }
        }

        //用于主页更新心愿单增删
        [HttpPost]
        public JsonResult AddWish(PurchaseHomeTotalInfo purchaseHomeTotalInfo)
        {
            Session.Remove("ReturnToWishList");
            string mem_phone = Session["mem_phone"].ToString();
            string goods_id = purchaseHomeTotalInfo.wish_goods_id;
            ShopBusinessLogic.MemberPurchase memberPurchase = new ShopBusinessLogic.MemberPurchase();
            if (memberPurchase.addWishList(mem_phone, goods_id)) { }
            else
            {
                memberPurchase.deleteWishList(mem_phone, goods_id);
            }
            /*memberPurchase.addWishList(mem_phone, goods_id);*/
            return Json("心愿单更新成功");
        }

        //更新心愿单，主要是在心愿单页删除心愿商品
        [HttpPost]
        public ActionResult Index(string DeleteWishId)
        {
            Session.Remove("ReturnToWishList");
            string mem_phone = Session["mem_phone"].ToString();
            string goods_id = DeleteWishId;
            ShopBusinessLogic.MemberPurchase memberPurchase = new ShopBusinessLogic.MemberPurchase();
            memberPurchase.deleteWishList(mem_phone, goods_id);
            var wish_list = memberPurchase.getWishLists(Session["mem_phone"].ToString()).Select(wish_info => new MemberWishListViewModel()
            {
                goods_id = wish_info.goods_id,
                goods_name = memberPurchase.getGoods(wish_info.goods_id).goods_name,
                goods_unit_price = memberPurchase.getGoods(wish_info.goods_id).goods_price,
                goods_img_path = memberPurchase.getGoods(wish_info.goods_id).goods_img_path,
            }).ToList();
            var resView = new MemberWishListViewModel()
            {
                mem_phone = Session["mem_phone"].ToString(),
                wish_lists = wish_list,
            };
            return PartialView("WishListPart1",resView);
        }

    }
}

ShopWeb/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/css/css")
    @Styles.Render("~/Content/vender/css")

    @Scripts.Render("~/Content/js/js")
    @Scripts.Render("~/Content/vender/js")

    <link rel="icon" type="image/png" href="~/content/fav.png">
    <style>
        .uil-heart.has_liked
        {
            color:orangered;
        }
        uil-heart.has_not_liked
        {
            color:gray;
        }
    </style>
</head>
<!-- Header Start -->
<header class="header clearfix">
    <div class="top-header-group">
        <div class="top-header">
            <a href=@Url.Content("~/Home")>
                <div class="cart__btn hover-btn uil-home-alt" style="height:60px;padding:20px 30px">
                    <span>主页</span>
                </div>
            </a>
            <a href=@Url.Content("~/PurchaseCar")>
                <div class="cart__btn hover-btn uil-shopping-cart-alt" style="height:60px;padding:20px 30px;">
                    <span>购物车</span>
                </div>
            </a>
            @*     <div class="center-block " margin-left:500px>
            @Html.ActionLink("心愿单", "Index", "WishList")
        </div>
            *@
            <div class="header_right">
                <ul>
                    <li>
                        <a href="@Url.Content("~/WishList")" class="option_links" title="Wishlist"><i class='uil uil-heart icon_wishlist'></i></a>
                    </li>
                    @if (Session["has_login"] == null)
                    {
                        @Html.ActionLink("登入", "Index", "Login", new { }, new { @style = "color:#f55d2c;margin:0 5px;" })
                        @Html.ActionLink("注册", "Index", "SignUp", new { }, new { @style = "color:#f55d2c;margin:0 5px;" })
                    }
                    @if (Session["has_login"] != null)
                    {
                        <li height="60px" class="ui dropdown " id="user_li">
                            <a href=@Url.Content("~/MemberInfo")>
                                <div class="opts_account" style="max-width: 150px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                                    <img src="~/Content/image/avatar/img-5.jpg" alt="">
                                                  <span class="user__name" style="width:80px;overflow:hidden;text-overflow :ellipsis;white-space:nowrap;"> @Session["mem_name"].ToString()</span>
                                    <i class="uil uil-angle-down"></i>
                                </div>
                            </a>
                            <div class="menu dropdown_account user_div" id="user_btn">
                                <div class="item channel_item"><i class="uil uil-apps icon__1"></i>@Html.ActionLink("我的信息", "Index", "MemberInfo", new { }, new { @style = "color:black" })</div>
                                <div class="item channel_item"><i class="uil uil-box icon__1"></i>@Html.ActionLink("我的订单", "Index", "PurchaseList", new { }, new { @style = "color:black" })</div>
                                <div class="item channel_item"><i class="uil uil-heart icon__1"></i>@Html.ActionLink("我的心愿单", "Index", "WishList", new { }, new { @style = "color:black" })</div>
                                <div class="item channel_item"><i class="uil uil-lock-alt icon__1"></i>@Html.ActionLink("注销", "LoginOut", "Login", new { }, new { @style = "color:black" })</div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- Header End -->
<body>
    <div class="wrapper" style="padding-top:60px;">
        @RenderBody()
    </div>

    <div class="copyright-text text-center mt-3">
        <i class="uil uil-copyright"></i>Copyright 2020 <b>MJX</b> . All rights <a href="" title="">researved</a>
    </div>


    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        $(function () {
            setTimeout(function () {
                $("#pwd_error_info,#phone_error_info").show();
                setTimeout(function () {
                    $("#pwd_error_info,#phone_error_info").hide();
                }, 2000);
            }, 0);
        });
    </script>
    <script>
        $(function () {
            $('#bar_01').owlCarousel(
                {
                    loop: true,
                    autoPlay: false,
                    navigation: true,
                    navigationText: ["上一个", "下一个"]
                });
            $('#bar_02').owlCarousel({

            });
            $('#bar_03').owlCarousel({

            });
        })
    </script>

    <script>
        $(function () {
            $(".add_cart").click(function () {
                $("#alert_message_cart").fadeIn("fast");
                setTimeout(function () { $("#alert_message_cart").fadeOut("slow"); }, 400)
            });

        });
        $(function () {
            $(".log_err").click(function () {
                $("#alert_message_log_err").fadeIn("fast");
                setTimeout(function () { $("#alert_message_log_err").fadeOut("slow"); }, 400)
            });

        });
        $(function () {
            $(".add_wish").click(function () {
                $("#alert_message_wish").fadeIn("fast");
                setTimeout(function () { $("#alert_message_wish").fadeOut("slow"); }, 400)
            });

        });
        $(function () {
            setTimeout(function () {
                $("#alert_message_cart").hide();
            }, 0)
        });
        $(function () {
            setTimeout(function () {
                $("#alert_message_wish").hide();
            }, 0)
        });
        $(function () {
            setTimeout(function () {
                $("#alert_message_log_err").hide();
            }, 0)
        });

        $(function () {
            setTimeout(function () {
                $("#init_page").hide();
            }, 0)
        });

        $(document).ready(function () {

            $("#user_li").hover(function () {
                let user_li = document.getElementById('user_li');
                let user_btn = document.getElementById('user_btn');
                user_li.classList.add("active")
                user_li.classList.add("visible")
                user_btn.classList.add("left")
                user_btn.classList.add("transition")
                user_btn.classList.add("visible")
                user_btn.classList.add("hidden")
                user_btn.classList.remove("hidden")
                user_btn.style.display = "display: block !important"


            },
                function () {
                });
        });

        $(document).ready(function () {

            $(".top-header-group").hover(function () {
            },
                function () {

                    let user_li = document.getElementById('user_li');
                    let user_btn = document.getElementById('user_btn');
                    user_li.classList.add("active")
                    user_li.classList.add("visible")
                    user_btn.classList.add("left")
                    user_btn.classList.add("transition")
                    user_btn.classList.add("visible")
                    user_btn.classList.add("hidden")
                    user_btn.classList.remove("visible")
                    user_li.classList.remove("active")
                    user_li.classList.remove("visible")


                });
        });
        $(document).ready(function () {

            var sync1 = $("#sync1");
            var sync2 = $("#sync2");
            var slidesPerPage = 4; //globaly define number of elements per page
            var syncedSecondary = true;

            sync1.owlCarousel({
                items: 1,
                slideSpeed: 2000,
                nav: true,
                autoplay: false,
                dots: false,
                loop: true,
                responsiveRefreshRate: 200,
                navText: ["<i class='uil uil-angle-left'></i>", "<i class='uil uil-angle-right'></i>"],
            }).on('changed.owl.carousel', syncPosition);

            sync2
                .on('initialized.owl.carousel', function () {
                    sync2.find(".owl-item").eq(0).addClass("current");
                })
                .owlCarousel({
                    items: slidesPerPage,
                    dots: true,
                    smartSpeed: 200,
                    slideSpeed: 500,
                    slideBy: slidesPerPage, //alternatively you can slide by 1, this way the active slide will stick to the first item in the second carousel
                    responsiveRefreshRate: 100,
                }).on('changed.owl.carousel', syncPosition2);

            function syncPosition(el) {
                //if you set loop to false, you have to restore this next line
                //var current = el.item.index;

                //if you disable loop you have to comment this block
                var count = el.item.count - 1;
                var current = Math.round(el.item.index - (el.item.count / 2) - .5);

                if (current < 0) {
                    current = count;
                }
                if (current > count) {
                    current = 0;
                }

                //end block

                sync2
                    .find(".owl-item")
                    .removeClass("current")
                    .eq(current)
                    .addClass("current");
                var onscreen = sync2.find('.owl-item.active').length - 1;
                var start = sync2.find('.owl-item.active').first().index();
                var end = sync2.find('.owl-item.active').last().index();

                if (current > end) {
                    sync2.data('owl.carousel').to(current, 100, true);
                }
                if (current < start) {
                    sync2.data('owl.carousel').to(current - onscreen, 100, true);
                }
            }

            function syncPosition2(el) {
                if (syncedSecondary) {
                    var number = el.item.index;
                    sync1.data('owl.carousel').to(number, 100, true);
                }
            }

            sync2.on("click", ".owl-item", function (e) {
                e.preventDefault();
                var number = $(this).index();
                sync1.data('owl.carousel').to(number, 300, true);
            });
        });
    </script>
</body>

</html>

ShopWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/css/css")
    @Styles.Render("~/Content/vender/css")

    @Scripts.Render("~/Content/js/js")
    @Scripts.Render("~/Content/vender/js")
    <link rel="icon" type="image/png" href="~/content/fav.png">
    <style>
        .uil-heart.has_liked {
            color: orangered;
        }

        uil-heart.has_not_liked {
            color: gray;
        }
    </style>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</body>
</html>

ShopWeb/Views/Shared/_SignLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css/css")
    @Styles.Render("~/Content/vender/css")
    @Scripts.Render("~/Content/js/js")
    @Scripts.Render("~/Content/vender/js")
    <link rel="icon" type="image/png" href="~/content/fav.png">
</head>
<header class="header clearfix">
    <div class="top-header-group">
        <div class="top-header">
            <a href="@Url.Content("~/Home")">
                <div class="cart__btn hover-btn uil-home-alt" style="height:60px;padding:20px 30px">
                    <span>主页</span>
                </div>
            </a>
        </div>
    </div>
</header>
<body>
    <div class="sign-inup">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="sign-form">
                        <div class="sign-inner">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(function () {
            setTimeout(function () {
                $("#pwd_error_info,#phone_error_info").show();
                setTimeout(function () {
                    $("#pwd_error_info,#phone_error_info").hide();
                }, 2000);
            }, 0);
        });
    </script>
</body>
</html>